
plugins:
  - serverless-plugin-split-stacks
  - serverless-aws-documentation

service: mensageo
#app: your-app-name
#tenant: your-tenant-name

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  stage: ${env:STAGE}
  region: ${env:AWSREGION}
  vpc:
    securityGroupIds:
      - ${env:AWSSECURITYGROUP}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

  environment:
    STAGE: ${env:STAGE}


custom:
  localstack:
    endpointFile: ./localstack.json

  splitStacks:
    perFunction: false
    perType: false

  documentation:
    api:
      info:
        version: "0.0.1"
        title: "mensageo backend"
        description: "mensageo API"
        termsOfService: "http://www.mensageo.com/terms-of-service"
        contact:
          name: "mensageo"
          url: "https://www.mensageo.com/"
          email: "info@mensageo.com"
        license:
          name: "MIT"
          url: "https://opensource.org/licenses/MIT"
      authorizers:
        -
          name: "CustomAuthorizer"
          description: "Authorization is not implemented yet"

    paramDescriptions:
      CorsHeaders: &CorsHeaders
        origin: '*'
        headers:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Amz-User-Agent
        allowCredentials: false

package:
  include:
    - models/**
    - handlers/**
    - knex/**
    - knexfile.js
    - lib/**

functions:


